version: '2.0'

services:

  zookeeper1:
    image: utuba/zookeeper:latest
    ports:
      - "2181:2181"
    command: ["-id", "1", "-s", "1=zookeeper1:2888:3888", "-s", "2=zookeeper2:2888:3888", "-s", "3=zookeeper3:2888:3888"]

  zookeeper2:
    image: utuba/zookeeper:latest
    ports:
      - "2281:2181"
    command: ["-id", "2", "-s", "1=zookeeper1:2888:3888", "-s", "2=zookeeper2:2888:3888", "-s", "3=zookeeper3:2888:3888"]

  zookeeper3:
    image: utuba/zookeeper:latest
    ports:
      - "2381:2181"
    command: ["-id", "3", "-s", "1=zookeeper1:2888:3888", "-s", "2=zookeeper2:2888:3888", "-s", "3=zookeeper3:2888:3888"]
